Add new functionality
elastio/block-utils pull request #4
Opened 2020-10-14 18:04 UTC by Apostoln

- Get children devices (partitions) for disk
 - Get property value for device

2020-10-14 18:06 UTC, Apostoln commented
@anelson
Note: This is a PR to fake branch for your review.

I'll create a PR to upstream after your approve.

2020-10-14 18:09 UTC, Apostoln commented
Note: I've missed that getting disk(parent device) for partition is already implemented in block-utils. So I've just implemented only  getting partitions(children) for disk and getting device's tags(properties).

2020-10-15 15:27 UTC, anelson requested changes

2020-10-15 15:27 UTC, anelson commented on src/lib.rs
> +    let error_message = format!(
Why incur the mem allocate and overhead for this message before you even have an error?  You could do this `format!` in the closure that creates the `BlockUtilsError`

2020-10-15 15:27 UTC, anelson commented on src/lib.rs
> +    let error_message = format!(
Same wasteful approach here

2020-10-18 16:52 UTC, anelson approved these changes

2020-10-23 14:29 UTC, merged